### PR TITLE
Quickstart update

### PR DESCRIPTION
**Pull request by jdeschamps**
Really like it!

Here are just some typo corrections, a conclusion and a little bit of reorganization in some sections.

### CODE REVIEW

**Comment by jdeschamps** [comment]
I'll go through what's in the tutorial on the same PR right now.

**Review by tlambert03 — APPROVED** [review]
Awesome!

**Comment by tlambert03** [comment]
Merge whenever

**Comment by jdeschamps** [comment]
Just fixing my local set-up (pre-commit hooks and vscode settings...) :)

**Pull request merged**
